config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root to: 'users#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[create new]
      resources :likes, only: %i[create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post
  validates :text, presence: true, length: { maximum: 1000 }
  after_save :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post
  after_save :update_likes_counter

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  after_save :update_posts_counter

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :email, presence: true, uniqueness: true

  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/UsersController.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :bio, :photo, current_password)
    end

    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @user = current_user
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @user = User.find(params[:user_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_url(@user, @post), notice: 'Comment created successfully!'
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to new_user_post_comment_url(@user, @post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = User.find(params[:user_id])
    @like = @post.likes.new
    @like.author = current_user

    if @like.save
      redirect_to user_post_url(@user, @post), notice: 'Like created successfully!'
    else
      flash[:errors] = @like.errors.full_messages
      redirect_to user_post_url(@user, @post)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author, comments: [:author])
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.author = User.find(params[:user_id])
    @user = User.find(params[:user_id])

    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post created successfully!'
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to new_user_post_path(@user)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with(model: [@post, Comment.new], url: user_post_comments_path(@user, @post)) do |form| %>
  <div class="field">
    <%= form.text_area :text, placeholder: "Write a comment..." %>
  </div>
  <div class="actions">
    <%= form.submit "Submit" %>
  </div>
  <%= render "shared/flashes" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "posts" %>
<div class="posts">
  <%= render "shared/user", user: @user %>
  <br>
  <br>
  <br>
  <% @posts.each do |post| %>
    <%= render "shared/post_preview", post: post, user: @user, trim: true %>
    <div class="comments-box">
      <% post.comments.each do |comment| %>
        <p class="comment"><%= comment.author.name %>:
          <%= comment.text %></p>
      <% end %>
    </div>
  <% end %>
  <button>
    <a href="<%= users_path %>">
      Go to all users
    </a>
  </button>
  <button>
    Pagination
  </button>
</div>

app/views/posts/new.html.erb
<%= form_with model: [@user, @post], url: user_posts_path(@user) do |form| %>
  <div class="form-title field">
    <%= form.label :title %>:
    <%= form.text_field :title %>
  </div>
  <div class="form-text field">
    <%= form.label :text %>:
    <%= form.text_area :text %>
  </div>
  <%= form.submit "Create Post" %>
  <%= render "shared/flashes" %>
<% end %>

app/views/posts/show.html.erb
<div class="post">
  <div class="post-box">
    <div class="post-info">
      <p>
        <%= @post.title %>
        by
        <%= @post.author.name %>
      </p>
      <p class="post-comments-and-likes">
        <%= pluralize(@post.comments.count, "comment") %>
        <%= pluralize(@post.likes.count, "like") %>
      </p>
    </div>
    <p class="post-body">
      <%= @post.text %>
    </p>
  </div>
  <%= form_with model: [@post, Like.new], url: user_post_likes_path(@user, @post) do |form| %>
    <div class="actions">
      <%= form.submit "Like this post" %>
    </div>
  <% end %>
  <br>
  <div class="posts-comments-box">
    <% @post.comments.includes(:author).each do |comment| %>
      <p class="comment">
        <a href="<%= user_path(comment.author) %>">
          <%= comment.author.name %></a>:
        <%= comment.text %></p>
    <% end %>
  </div>
  <a href="<%= new_user_post_comment_path(@user, @post) %>">Add a comment</a>
  <br>
  <br>
  <button>
    <a href="<%= user_posts_path(@user) %>" class="post-link">
      Go to all posts
    </a>
  </button>
  <%= render "shared/flashes" %>
</div>

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="flash <%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/_post_preview.html.erb
<div class="post-preview-partial">
  <p class="post-info">
    <a href="<%= user_post_path(user, post) %>">
      <p><%= post.title %></p>
    </a>
    <p class="comments-and-likes">
      <%= pluralize(post.comments.count, "comment") %>
      <%= pluralize(post.likes.count, "like") %>
    </p>
  </p>
  <p class="post-content <%= 'trim' if trim %>">
    <%= post.text %>
  </p>
  <br>
</div>

app/views/shared/_posts_preview.html.erb
<div class="post-preview-partial">
  <p class="post-info">
    <a href="<%= user_post_path(@user, post) %>">
      <p><%= post.title %></p>
    </a>
    <p class="comments-and-likes">Comments:
      <%= post.comments_counter %>, likes:
      <%= post.likes_counter %></p>
  </p>
  <p class="post-content">
    <%= post.text %>
  </p>
</div>

app/views/shared/_user.html.erb
<div class="user-partial">
  <img src="<%= user.photo %>" alt="avatar"/>
  <div class="user-info">
    <a href="<%= user_path(user) %>">
      <h3><%= user.name %></h3>
    </a>
    <p class="num-of-posts">Number of posts:
      <%= user.posts_counter %></p>
  </div>
</div>

app/views/users/index.html.erb
<div class="users">
  <div class="nav">
    <% if user_signed_in? %>
      <p class="signed-in-as">Signed in as:
        <%= current_user.name %>
      </p>
      <%= link_to "Sign out",
      destroy_user_session_path,
      data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure you want to log out?"
      },
      class: "signout" %>
    <% end %>
  </div>
  <ul class="users-list">
    <% @users.each do |user| %>
      <li class="users-list-item">
        <%= render "shared/user", user: user %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="user">
  <%= render "shared/user", user: @user %>
  <section class="user-bio">
    <h2>Bio</h2>
    <p><%= @user.bio %></p>
  </section>
  <section class="user-posts-preview">
    <% @user.posts.limit(3).each do |post| %>
      <%= render "shared/post_preview", post: post, user: @user, trim: true %>
    <% end %>
  </section>
  <button class="all-posts-btn">
    <a href="<%= user_posts_path(@user) %>">See all posts</a>
  </button>
</div>